### ISSUE TITLE
Zombienet SDK PoC (native provider)

### ISSUE THREAD

**Issue by pepoviola** [paritytech/zombienet-sdk#60]
# The Vision

As part of the building of the new SDK (#1), we want to create a `PoC` with a subset of features (spawning only) to collect feedback from the internal teams.

# The Plan

The subset of features we want to achieve in this `Poc`:

- [x] #24 : Responsible for creating the configuration (`./crates/configuration`)
- [x] #26: Responsible for bringing the state of the running network to the expected configuration and managing it in real-time (`./crates/orchestrator`)
- [x] #37 (provide basic functionality for spawn a network)
- [x] Port some of the `examples` from https://github.com/paritytech/zombienet/tree/main/examples
- [x] https://github.com/paritytech/zombienet-sdk/issues/80

```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/zombienet-sdk/issues/24
- [ ] https://github.com/paritytech/zombienet-sdk/issues/26
- [ ] https://github.com/paritytech/zombienet-sdk/issues/37
- [x] Port some of the examples from https://github.com/paritytech/zombienet/tree/main/examples
- [x] https://github.com/paritytech/zombienet-sdk/issues/80
```

**Comment by pepoviola** [comment]
PoC for `native` is ready, closing here.
