### ISSUE TITLE
[Providers] Add docker support

### ISSUE THREAD

**Issue by pepoviola** [paritytech/zombienet-sdk#63]
# The Vision

Zombienet provides multiple `providers` to allow users run their networks where they need (e.g k8s, podman, native). We want to keep adding support for other providers and we think that adding `docker` as provider will allow newcomers to easily start using zombienet and will create a more smooth setup/introduction of the features that we provide.

# The Plan

Ones we have an stable version of the `sdk` we will start working on this tasks to add `docker` as provider option.

# Tasks

- [x] https://github.com/paritytech/zombienet-sdk/issues/38
- [x] https://github.com/paritytech/zombienet-sdk/issues/61
- [x] https://github.com/paritytech/zombienet-sdk/issues/62

**Comment by pepoviola** [comment]
Done, docker is the default provider in `environment` from `sdk` crate.
Thx!
